In [1]:
import pandas as pd

df = pd.read_csv('forestfires.csv')
df

X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area  \
0    7  5   mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00   
1    7  4   oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00   
2    7  4   oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00   
3    8  6   mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00   
4    8  6   mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00   
..  .. ..   ...  ...   ...    ...    ...   ...   ...  ..   ...   ...    ...   
512  4  3   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44   
513  2  4   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29   
514  7  4   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16   
515  1  4   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00   
516  6  3   nov  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00   

     fire  
0       0  
1       0  
2       0  
3       0  
4       0  
..    ...  
512     1  
513     1  
514     1  
515     0  
516     0  

[517 rows x 14 columns]

In [2]:
#Support Vector Algorithm
import matplotlib.pyplot as plt

plt.style.use('ggplot')

df = pd.read_csv('forestfires.csv')
df.shape


(517, 14)

In [3]:
#defining features and targets

x = df.drop('fire',axis=1)
y = df['fire']

In [4]:
# removing string attributes
x = x.drop(['month','day'],axis=1)
x

X  Y  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
0    7  5  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00
1    7  4  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00
2    7  4  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00
3    8  6  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00
4    8  6  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00
..  .. ..   ...    ...    ...   ...   ...  ..   ...   ...    ...
512  4  3  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44
513  2  4  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29
514  7  4  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16
515  1  4  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00
516  6  3  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00

[517 rows x 11 columns]

In [5]:
y

0      0
1      0
2      0
3      0
4      0
      ..
512    1
513    1
514    1
515    0
516    0
Name: fire, Length: 517, dtype: int64

In [6]:
#splitting the dataset into train and test using sklearn 

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.20)

In [7]:
#importing support vector classifier function or SVC func from SVM module

from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(x_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [8]:
#predict values using the svm agorithm model

y_pred = svclassifier.predict(x_test)

In [9]:
#evaluate the support vector machine model

from sklearn.metrics import classification_report, confusion_matrix
print("Confusion Matrix\n")
print(confusion_matrix(y_test,y_pred))
print("\nClassification Report\n")
print(classification_report(y_test,y_pred))

Confusion Matrix

[[55  0]
 [ 0 49]]

Classification Report

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        55
           1       1.00      1.00      1.00        49

    accuracy                           1.00       104
   macro avg       1.00      1.00      1.00       104
weighted avg       1.00      1.00      1.00       104



# Implementing kernel SVM with sklearn SVM module

In [10]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Gaussian Kernel

In [11]:

from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

svclassifier2 = SVC(kernel='rbf')
svclassifier2.fit(x_train,y_train)

#making predictions
y_pred2 = svclassifier2.predict(x_test)

#Evaluation the model
print("Confusion Matrix\n",confusion_matrix(y_test,y_pred2))
print("\nClassification Report\n",classification_report(y_test,y_pred2))

Confusion Matrix
 [[10 45]
 [ 1 48]]

Classification Report
               precision    recall  f1-score   support

           0       0.91      0.18      0.30        55
           1       0.52      0.98      0.68        49

    accuracy                           0.56       104
   macro avg       0.71      0.58      0.49       104
weighted avg       0.72      0.56      0.48       104



C:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


## Sigmoid Kernel

In [12]:

from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

svclassifier3 = SVC(kernel='sigmoid')
svclassifier3.fit(x_train,y_train)

#making predictions
y_pred3 = svclassifier3.predict(x_test)

#Evaluation the model
print("Confusion Matrix\n",confusion_matrix(y_test,y_pred3))
print("\nClassification Report\n",classification_report(y_test,y_pred3))

C:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


Confusion Matrix
 [[ 0 55]
 [ 0 49]]

Classification Report
               precision    recall  f1-score   support

           0       0.00      0.00      0.00        55
           1       0.47      1.00      0.64        49

    accuracy                           0.47       104
   macro avg       0.24      0.50      0.32       104
weighted avg       0.22      0.47      0.30       104



C:\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
